### ISSUE TITLE
Dropbox links seem invalid

### ISSUE THREAD

**Issue by yzcjtr** [jimeiyang/objectContourDetector#1]
Hi Jimei, I tried to download the pretrained model while the dropbox link seems expired. Can you update it?

**Comment by jimeiyang** [comment]
Hi, I just tested the link in the US and it is valid. If you're downloading the model from somewhere else, you may need VPN?

**Comment by zhijinghe** [comment]
Hi,Jimei,I have also tried to download the model and the data,but the dropbox link shows that" the file is nolonger here, The file may have been moved or set as private." ps:I have use the VPN.Can you check the address again if it is available,thank you very much!

**Comment by jimeiyang** [comment]
I have updated the model url. Please try again.
